spring:
  profiles:
    active: local
pakgopay:
  currency-sync:
    excel-url: https://raw.githubusercontent.com/zhangxiangyangdebug/PakGoPay/main/packgopay/src/main/resources/excel/currency-types.xlsx
  bankCode-sync:
    excel-url: https://raw.githubusercontent.com/zhangxiangyangdebug/PakGoPay/main/packgopay/src/main/resources/excel/bank-code.xlsx